### PR TITLE
Update ADAL.Android SDK to 1.12.0

### PR DESCRIPTION
**Pull request by okulygin**

### CODE REVIEW

**Comment by vladimir-kotikov** [comment]
@matrosov-nikita could you please take a look and test this?

**Comment by matrosov-nikita** [comment]
@okulygin, thanks for submitting, could you please answer a few questions?
Can we add runner to thread pool for non-silent token acquisition?
Why did you remove logic for requesting broker permissions?

**Comment by matrosov-nikita** [comment]
@okulygin, just a friendly ping.

**Comment by okulygin** [comment]
I have removed logic for requesting broker permissions because ADAL.Android does not require Contacts permission anymore. See https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/changelog.txt#L6

**Comment by matrosov-nikita** [comment]
@vladimir-kotikov, 2 auto-test are failed in case of using broker cache. I'm going to take a look at this.

**Comment by vladimir-kotikov** [comment]
@matrosov-nikita sounds good. Let me know once everything is done and I'll merge this

**Comment by matrosov-nikita** [comment]
@vladimir-kotikov, these changes look good for me, some of the auto-tests are failed due to empty adal cache in case of using a broker, so it's expected behavior.

**Comment by vladimir-kotikov** [comment]
Thanks, @matrosov-nikita. @okulygin may I ask you to rebase this PR on top of master branch?

**Comment by vladimir-kotikov** [comment]
Merged. @okulygin, thanks!

**Pull request merged**
